### PR TITLE
Implement get_all_messages function

### LINKED ISSUE #27: Get all messages as a stream

### PR DESCRIPTION
**Pull request by alexrudd**
Basically just a copy of `get_category_messages` but with all category filtering removed. It didn't make sense for all tests to be copied, as, without filtering, they end up returning messages from other tests.

Likely there are things missing from this PR so let me know what else would need doing :)

Closes: #27

### CODE REVIEW

**Comment by alexrudd** [comment]
Thinking about this a bit more, the better approach might be to unify get_category_messages and get_all_messages into a single get_messages that takes category as an optional argument.

**Comment by sbellware** [comment]
For what it's worth, it would be considered largely an anti-pattern to process all messages in the entire message store. In practice, there's no real need for any given component or service to need to subscribe to messages from every other component. Components almost always subscribe to a very small number of categories that are pertinent to the single, cohesive purpose of the component. There's no real need in practice for the message streams equivalent of global memory, and all of the traps and setbacks due to unconstrained coupling that goes with it.

I'm very leery of adding capability to Message DB that would largely contradict the practices and patterns that lead to keep projects from going off the rails.

There are indeed some data analytics applications that benefit from accessing all messages irrespective of their category, but data applications are free to do what they wish with the message data. That's ultimately the value of using something like Postgres to model message stream-based storage and retrieval: when the special needs of data analytics come up, SQL is the right solution.

**Comment by alexrudd** [comment]
Understandable. The use case I had in mind was what you suggested - we need to ship all our events off to an analytics provider. It would be nice to have access to the consumer groups feature for this, but there's no reason I couldn't implement that as a query.

**Comment by sbellware** [comment]
Indeed, what you're talking about is bulk ETL, rather than stream processing. I would point out that it's the messiest way to move data into analytics pipeline. While it may seem to be an expeditious way to proceed - ie: just get the data over to the analytics store, and worry about it later - you may find later that this kind of bulk ETL may cause you setbacks and delays far beyond any perceived time savings that would come from processing categories explicitly. It's not guaranteed to be so fraught, but it is a risk that is invited that would otherwise be excluded by using category-oriented data transfer.

In the end, the consumer groups feature of Message DB depends entirely on a category name to calculate the consumer group member number to resolve the streams to be processed by any member of a consumer group. This reflects the sole design intent of Message DB to back transactional stream processing applications. There would be no practical solution for using consumer groups with a query for all messages that is not discriminated by a category. Technically, it would be somewhat of an absurdity relative to Message DB's consumer group implementation, and would require an entirely different consumer group information to support a use case that ultimately is something that is architecturally less desirable.

I think that there's a reasonable chance that if we were to dig in deeper into your use case, that you might find better solutions for analytics data transfer by leveraging the inherent constraints of working within stream categories, rather than trying to process the entire bulk of the contents of a message store. It's possible that whatever analytics tool is on the other side of the architecture is imposing harder constraints that you need to work with, though. In that case, you might be left with few options other than bulk ETL.

**Comment by shinzui** [comment]
>  Components almost always subscribe to a very small number of categories that are pertinent to the single, cohesive purpose of the component. 

@sbellware How do you currently get messages from multiple stream categories with a single query?

**Pull request closed without merging**
